package com.mtd.crypto.trader.common.enumarator;

public enum TradeStatus {
    APPROVAL_WAITING,
    POSITION_WAITING,
    CANCELLED_BEFORE_POSITION,
    EXPIRED,
    IN_POSITION,
    CLOSED_IN_POSITION,
    POSITION_FINISHED_WITH_PROFIT,
    POSITION_FINISHED_WITH_LOSS
}
