spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
  datasource:
    url: jdbc:mysql://localhost:3308/crypto
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        #implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        # dialect: org.hibernate.dialect.H2Dialect
        dialect: org.hibernate.dialect.MySQLDialect

        #format_sql: true
        #id:
        # new_generator_mappings: false
    show-sql: true

app:
  binance:
    secure:
      secret-key: ${BINANCE_SECRET}
      api-key: ${BINANCE_API_KEY}
    trade:
      max-allowed-dollars-trade: 100

    url:
      api: https://testnet.binance.vision
      backup-apis:
        - https://api1.binance.com
        - https://api2.binance.com
        - https://api2.binance.com
      path:
        system-status: /sapi/v1/system/status
        wallet: /sapi/v1/capital/config/getall
        account: /api/v3/account
        price: /api/v3/ticker/price
        klines: /api/v3/klines
        exchange-info: /api/v3/exchangeInfo
        normal-order: /api/v3/order
        open-orders: /api/v3/openOrders
        oco-order: /api/v3/order/oco
        oco-order-list: /api/v3/orderList
        oco-open-order-list: /api/v3/openOrderList
        oco-all-order-list: /api/v3/allOrderList
        my-trades: /api/v3/myTrades

  telegram:
    api-key: ${TELEGRAM_API_KEY}
    chat-id: ${TELEGRAM_MAIN_CHAT_ID}
    base-url: https://api.telegram.org/bot

  trading:
    normal:
      strategy:
        price-drop-safe-entry-percentage: 0.01
        partial-exit-percentage-step: 0.33
        safe-exit-percentage: 0.99
      cron:
        position-enter: '-'
        position-exit: '-'
      notification:
        telegram:
          error-channel-id: ${TELEGRAM_ERROR_CHANNEL_ID}
          info-channel-id: ${TELEGRAM_INFO_CHANNEL_ID}
          report-channel-id: ${TELEGRAM_REPORT_CHANNEL_ID}











