# Use root/example as user/password credentials
version: '3.8'

services:
  db:
    image: arm64v8/mysql
    container_name: crpto-database
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - database-volume:/var/lib/mysql
      - ./mysql-scripts:/docker-entrypoint-initdb.d:ro
    ports:
      - 3308:3306

volumes:
  database-volume:
